name: Build

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v7.0.0

      - name: Free Runner Disk Space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true

      - name: Check Disk Space
        run: df -h

      - name: Setup Java
        uses: actions/setup-java@v5.5.0
        with:
          distribution: zulu
          java-version: 21

      - name: Build plugin
        run: ./gradlew buildPlugin

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: plugin-distribution
          path: ./build/distributions/*.zip

  test:
    name: Test
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v7.0.0

      - name: Setup Java
        uses: actions/setup-java@v5.5.0
        with:
          distribution: zulu
          java-version: 21

      - name: Run Tests
        run: ./gradlew check

      - name: Collect Tests Result
        if: ${{ failure() }}
        uses: actions/upload-artifact@v7
        with:
          name: tests-result
          path: ${{ github.workspace }}/build/reports/tests

  verify:
    name: Verify plugin
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v7.0.0

      - name: Setup Java
        uses: actions/setup-java@v5.5.0
        with:
          distribution: zulu
          java-version: 21

      - name: Run Plugin Verification tasks
        run: ./gradlew verifyPlugin

      - name: Collect Plugin Verifier Result
        if: ${{ always() }}
        uses: actions/upload-artifact@v7
        with:
          name: pluginVerifier-result
          path: ${{ github.workspace }}/build/reports/pluginVerifier
